name: build/test

on:
  push:
  schedule:
    - cron: '30 5 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - windows-2019

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '3.1.x'

      - name: Dotnet linter
        run: |
          dotnet tool install -g dotnet-format
          dotnet format . --check

      - name: TestOnSpot
        id: runonspot
        continue-on-error: true
        if: always()
        uses: ./.github/actions/test
        with:
          client_id: test
          client_secret: ${{ secrets.CLIENT_SECRET }}
          client_credentials_url: ${{ secrets.CLIENT_CREDENTIALS_URL }}

      - name: TestOnRegular
        id: runonregular
        if: steps.runonspot.outcome != 'success'
        uses: ./.github/actions/test
        with:
          client_id: test
          client_secret: ${{ secrets.CLIENT_SECRET }}
          client_credentials_url: ${{ secrets.CLIENT_CREDENTIALS_URL }}
